module.exports = {
  TRANSLATIONS: {
    en: {
      spin: 'Spin',
      community: 'Community',
      market: 'Market',
      profile: 'Profile',
      weight: 'Weight',
      diet: 'Diet',
      regular: 'Regular',
      vegan: 'Vegan',
      budget: 'Daily Budget',
      spinBtn: 'SPIN',
      latest: 'Latest',
      findChef: 'Find Chef',
      acceptOrders: 'Accept Orders',
      nearby: 'Nearby Chefs',
      requests: 'Live Requests',
      streak: 'Streak',
      wallet: 'Wallet',
      away: 'away',
      response: 'Response',
      online: 'Online',
    },
    zh: {
      spin: '摇号',
      community: '社区',
      market: '代厨',
      profile: '我的',
      weight: '体重',
      diet: '饮食偏好',
      regular: '常规',
      vegan: '纯素',
      budget: '每日预算',
      spinBtn: '摇一摇',
      latest: '最新',
      findChef: '找厨师',
      acceptOrders: '接单',
      nearby: '附近厨师',
      requests: '实时需求',
      streak: '连续打卡',
      wallet: '钱包',
      away: '距离',
      response: '响应',
      online: '在线',
    },
  },
};
